# ---MLP Networks for PPO-CRL (smaller, faster training)---
actor_network:
  pre_torso:
    _target_: mava.networks.torsos.MLPTorso
    layer_sizes: [512, 512, 512, 512]
    use_layer_norm: true
    activation: swish
    activate_final: true

sa_encoder_network:
  pre_torso:
    _target_: mava.networks.torsos.MLPTorso
    layer_sizes: [512, 512, 512, 512]
    use_layer_norm: true
    activation: swish
    activate_final: true

goal_encoder_network:
  pre_torso:
    _target_: mava.networks.torsos.MLPTorso
    layer_sizes: [512, 512, 512, 512]
    use_layer_norm: true
    activation: swish
    activate_final: true
